{% set name = "ge25519" %}
{% set version = "1.5.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 54a0cf89276e7d6c2b35c652453072154e181a826b9b8f130e6d67b785727250

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv
  skip: True  # [py<38]

requirements:
  host:
    - python
    - setuptools
    - wheel
    - pip
  run:
    - python
    - fe25519 >=1.5,<2.dev0

test:
  imports:
    - ge25519
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/nthparty/ge25519
  summary: Pure-Python data structure for working with Ed25519 (and Ristretto) field elements and operations.
  license: MIT
  license_family: MIT
  license_file: LICENSE
  description: |
    This library provides a native Python implementation of Ed25519 field elements and a number of operations over them.
  doc_url: https://ge25519.readthedocs.io
  dev_url: https://github.com/nthparty/ge25519

extra:
  recipe-maintainers:
    - Arishamays1
